ALTER TABLE schedule ADD COLUMN enabled BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE schedule ADD COLUMN status VARCHAR(30) NOT NULL;
ALTER TABLE schedule ADD COLUMN config JSONB NOT NULL DEFAULT '{}';
